### ISSUE TITLE
Separate passing targeted regions for "scope of protection" vs. "secuirty functions" in the parameters

### ISSUE THREAD

**Issue by muram** [alertlogic/mdr_control_tower_automation#17]
We should use 2 separate parameters and pass them to the onboarding function accordingly:

```yaml
  TargetRegion:
    Type: CommaDelimitedList
    Description: Target regions for AlertLogic deployment

  SecuirtySetupRegion:
      Type: String
      Description: Target region for AlertLogic Security account deployment
```

@ptrakhtman
